import 'package:flutter/material.dart';
import 'package:flutterapp/madapp/generatedgwidget2/generated/GeneratedIcontylLineArrowLeftWidget2.dart';
import 'package:flutterapp/madapp/generatedgwidget2/generated/GeneratedIngredientsWidget2.dart';
import 'package:flutterapp/madapp/generatedgwidget2/generated/GeneratedRectangle10Widget6.dart';
import 'package:flutterapp/madapp/generatedgwidget2/generated/GeneratedGerechtWidget2.dart';
import 'package:flutterapp/madapp/generatedgwidget2/generated/GeneratedFrame9Widget5.dart';
import 'package:flutterapp/madapp/generatedgwidget2/generated/GeneratedDoubleBurgerWidget.dart';
import 'package:flutterapp/madapp/generatedgwidget2/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/madapp/generatedgwidget2/generated/GeneratedcupnonfatvanillaGreekyogurtcuppartskimricottateaspoonle2.dart';
import 'package:flutterapp/madapp/generatedgwidget2/generated/GeneratedFrame9Widget4.dart';
import 'package:flutterapp/madapp/generatedgwidget2/generated/GeneratedRectangle10Widget7.dart';

/* Frame G
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(9.0, 4.0),
            blurRadius: 21.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(15.0),
        child: Container(
          width: 390.0,
          height: 844.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(15.0),
          ),
          child: Stack(
              clipBehavior: Clip.none,
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(15.0),
                  child: Container(
                    color: Color.fromARGB(255, 154, 224, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 293.0,
                  right: null,
                  bottom: null,
                  width: 414.0,
                  height: 603.0,
                  child: GeneratedRectangle10Widget6(),
                ),
                Positioned(
                  left: 53.0,
                  top: 205.0,
                  right: null,
                  bottom: null,
                  width: 308.0,
                  height: 194.0,
                  child: GeneratedRectangle10Widget7(),
                ),
                Positioned(
                  left: 136.0,
                  top: 56.0,
                  right: null,
                  bottom: null,
                  width: 119.0,
                  height: 31.0,
                  child: GeneratedGerechtWidget2(),
                ),
                Positioned(
                  left: 53.0,
                  top: 56.0,
                  right: null,
                  bottom: null,
                  width: 26.0,
                  height: 35.0,
                  child: GeneratedIcontylLineArrowLeftWidget2(),
                ),
                Positioned(
                  left: 129.0,
                  top: 425.0,
                  right: null,
                  bottom: null,
                  width: 160.0,
                  height: 25.0,
                  child: GeneratedDoubleBurgerWidget(),
                ),
                Positioned(
                  left: 11.0,
                  top: 539.0,
                  right: null,
                  bottom: null,
                  width: 352.0,
                  height: 169.0,
                  child:
                      GeneratedcupnonfatvanillaGreekyogurtcuppartskimricottateaspoonle2(),
                ),
                Positioned(
                  left: 11.0,
                  top: 496.0,
                  right: null,
                  bottom: null,
                  width: 142.0,
                  height: 17.0,
                  child: GeneratedIngredientsWidget2(),
                ),
                Positioned(
                  left: 271.0,
                  top: 493.0,
                  right: null,
                  bottom: null,
                  width: 63.638710021972656,
                  height: 30.051612854003906,
                  child: GeneratedFrame9Widget4(),
                ),
                Positioned(
                  left: 83.0,
                  top: 205.0,
                  right: null,
                  bottom: null,
                  width: 248.0,
                  height: 194.0,
                  child: GeneratedFrame9Widget5(),
                ),
                Positioned(
                  left: 80.0,
                  top: 206.0,
                  right: null,
                  bottom: null,
                  width: 251.0,
                  height: 193.0,
                  child: GeneratedFrame8Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
