import 'package:flutter/material.dart';
import 'package:flutterapp/madapp/generateddieetwidget/generated/GeneratedAdvertentiesWidget.dart';
import 'package:flutterapp/madapp/generateddieetwidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/madapp/generateddieetwidget/generated/GeneratedChooseDieetWidget.dart';
import 'package:flutterapp/madapp/generateddieetwidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/madapp/generateddieetwidget/generated/GeneratedFood011Widget.dart';
import 'package:flutterapp/madapp/generateddieetwidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/madapp/generateddieetwidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/madapp/generateddieetwidget/generated/GeneratedRectangle18Widget.dart';

/* Frame Dieet
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDieetWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(9.0, 4.0),
            blurRadius: 21.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(15.0),
        child: Container(
          width: 390.0,
          height: 844.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(15.0),
          ),
          child: Stack(
              clipBehavior: Clip.none,
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(15.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 47.0,
                  top: 175.0,
                  right: null,
                  bottom: null,
                  width: 296.0,
                  height: 56.0,
                  child: GeneratedGroup19Widget(),
                ),
                Positioned(
                  left: 47.0,
                  top: 321.0,
                  right: null,
                  bottom: null,
                  width: 296.0,
                  height: 56.0,
                  child: GeneratedGroup23Widget(),
                ),
                Positioned(
                  left: 47.0,
                  top: 467.0,
                  right: null,
                  bottom: null,
                  width: 296.0,
                  height: 56.0,
                  child: GeneratedGroup22Widget(),
                ),
                Positioned(
                  left: 52.0,
                  top: 613.0,
                  right: null,
                  bottom: null,
                  width: 296.0,
                  height: 56.0,
                  child: GeneratedGroup21Widget(),
                ),
                Positioned(
                  left: 17.0,
                  top: 25.0,
                  right: null,
                  bottom: null,
                  width: 356.0,
                  height: 74.0,
                  child: GeneratedFood011Widget(),
                ),
                Positioned(
                  left: 98.0,
                  top: 53.0,
                  right: null,
                  bottom: null,
                  width: 196.0,
                  height: 34.0,
                  child: GeneratedChooseDieetWidget(),
                ),
                Positioned(
                  left: 82.0,
                  top: 817.0,
                  right: null,
                  bottom: null,
                  width: 225.0,
                  height: 27.0,
                  child: GeneratedRectangle18Widget(),
                ),
                Positioned(
                  left: 150.0,
                  top: 823.0,
                  right: null,
                  bottom: null,
                  width: 95.0,
                  height: 21.0,
                  child: GeneratedAdvertentiesWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
