import 'package:flutter/material.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedFrame10Widget.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedAdvertentiesWidget1.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedIcontylLineArrowLeftWidget3.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedRectangle11Widget3.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedNootenWidget1.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedShutterstock_1438232087scaled1Widget.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedFrame9Widget6.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedGerechtenWidget1.dart';
import 'package:flutterapp/madapp/generatedgerechtenwidget/generated/GeneratedFood011Widget1.dart';

/* Frame Gerechten
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGerechtenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(9.0, 4.0),
            blurRadius: 21.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(15.0),
        child: Container(
          width: 390.0,
          height: 844.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(15.0),
          ),
          child: Stack(
              clipBehavior: Clip.none,
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(15.0),
                  child: Container(
                    color: Color.fromARGB(255, 154, 224, 255),
                  ),
                ),
                Positioned(
                  left: 17.0,
                  top: 25.0,
                  right: null,
                  bottom: null,
                  width: 356.0,
                  height: 74.0,
                  child: GeneratedFood011Widget1(),
                ),
                Positioned(
                  left: 120.0,
                  top: 46.0,
                  right: null,
                  bottom: null,
                  width: 155.0,
                  height: 37.0,
                  child: GeneratedGerechtenWidget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 293.0,
                  right: null,
                  bottom: null,
                  width: 414.0,
                  height: 603.0,
                  child: GeneratedRectangle11Widget3(),
                ),
                Positioned(
                  left: 30.000011444091797,
                  top: 309.0,
                  right: null,
                  bottom: null,
                  width: 330.5677490234375,
                  height: 192.68385314941406,
                  child: GeneratedGroup5Widget(),
                ),
                Positioned(
                  left: 30.0,
                  top: 86.0,
                  right: null,
                  bottom: null,
                  width: 330.56781005859375,
                  height: 200.05160522460938,
                  child: GeneratedGroup4Widget(),
                ),
                Positioned(
                  left: 296.0,
                  top: 479.0,
                  right: null,
                  bottom: null,
                  width: 63.638710021972656,
                  height: 30.051612854003906,
                  child: GeneratedFrame9Widget6(),
                ),
                Positioned(
                  left: 291.0,
                  top: 717.0,
                  right: null,
                  bottom: null,
                  width: 63.638710021972656,
                  height: 30.051612854003906,
                  child: GeneratedFrame10Widget(),
                ),
                Positioned(
                  left: 28.0,
                  top: 540.0,
                  right: null,
                  bottom: null,
                  width: 331.0,
                  height: 163.0,
                  child: GeneratedShutterstock_1438232087scaled1Widget(),
                ),
                Positioned(
                  left: 28.0,
                  top: 716.0,
                  right: null,
                  bottom: null,
                  width: 59.0,
                  height: 31.0,
                  child: GeneratedNootenWidget1(),
                ),
                Positioned(
                  left: 82.0,
                  top: 817.0,
                  right: null,
                  bottom: null,
                  width: 225.0,
                  height: 27.0,
                  child: GeneratedRectangle18Widget1(),
                ),
                Positioned(
                  left: 149.0,
                  top: 822.0,
                  right: null,
                  bottom: null,
                  width: 95.0,
                  height: 21.0,
                  child: GeneratedAdvertentiesWidget1(),
                ),
                Positioned(
                  left: 53.0,
                  top: 52.0,
                  right: null,
                  bottom: null,
                  width: 26.0,
                  height: 35.0,
                  child: GeneratedIcontylLineArrowLeftWidget3(),
                )
              ]),
        ),
      ),
    ));
  }
}
