import 'package:flutter/material.dart';
import 'package:flutterapp/madapp/generatedentrywidget/generated/GeneratedWelcometoDieetWidget.dart';
import 'package:flutterapp/madapp/generatedentrywidget/generated/GeneratedArrowbuttonWidget.dart';
import 'package:flutterapp/madapp/generatedentrywidget/generated/GeneratedImage1Widget.dart';

/* Frame Entry
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEntryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(9.0, 4.0),
            blurRadius: 21.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(15.0),
        child: Container(
          width: 390.0,
          height: 844.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(15.0),
            gradient: LinearGradient(
              begin: Alignment(0.0, -1.0),
              end: Alignment(0.0, 0.9999999999999998),
              stops: [0.0, 1.0],
              colors: [
                Color.fromARGB(255, 172, 182, 229),
                Color.fromARGB(102, 0, 255, 210)
              ],
            ),
          ),
          child: Stack(
              clipBehavior: Clip.none,
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Positioned(
                  left: 0.0,
                  top: 707.0,
                  right: null,
                  bottom: null,
                  width: 379.0,
                  height: 41.0,
                  child: GeneratedWelcometoDieetWidget(),
                ),
                Positioned(
                  left: -149.00669860839844,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 563.340087890625,
                  height: 716.3046875,
                  child: GeneratedImage1Widget(),
                ),
                Positioned(
                  left: 145.0,
                  top: 766.0,
                  right: null,
                  bottom: null,
                  width: 125.0,
                  height: 52.0,
                  child: GeneratedArrowbuttonWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
